[Variables]

;=== URL TO CUSTOM REDDIT MULTIFEED ===
URL=
;URL should look like: https://www.reddit.com/user/[your username]/m/[custom feed name].rss

;=== FONT CHOICE ===
Font=8
;1 - Microsoft JhengHei UI
;2 - Century Gothic
;3 - Eras Medium ITC
;4 - Futura Lt
;5 - Lato
;6 - Montserrat
;7 - Montserrat Light
;8 - Quicksand Medium
;9 - Segoe UI
;10 - Comfortaa Light

;=== FEED SPACING ===
EntrySpacing=5
LineSpacing=5
;Values are specified in pixels
