[Variables]

;=== USERNAME ===
Username=
;Enter your Reddit username

;=== URL TO CUSTOM REDDIT MULTIFEED ===
URL=
;URL should look like this: https://www.reddit.com/user/[your username]/m/[custom feed name].rss

;=== URL TO SINGLE-POST RSS ===
URLSingle=https://www.reddit.com/search.rss?q=subreddit%3Awallpaper%20self%3A0&sort=new
;Place an image-only rss feed url here

;=== FONT CHOICE ===
Font=8
;1 - Microsoft JhengHei UI
;2 - Century Gothic
;3 - Eras Medium ITC
;4 - Futura Lt
;5 - Lato
;6 - Montserrat
;7 - Montserrat Light
;8 - Quicksand Medium
;9 - Segoe UI
;10 - Comfortaa Light

;=== FEED SETTINGS ===
EntrySpacing=5
LineSpacing=5
;Spacing between objects, values are specified in pixels
